server:
  port: 8080
  servlet:
    context-path: /QuanLiChiTieu
  tomcat:
    max-http-post-size: 100MB
    max-swallow-size: 100MB

spring:
  application:
    name: AppQuanLiChiTieu

  datasource:
    url: ${DB_URL:jdbc:sqlserver://localhost;databaseName=Project_Exe1;encrypt=true;trustServerCertificate=true}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:sa}
    driver-class-name: ${DB_DRIVER:com.microsoft.sqlserver.jdbc.SQLServerDriver}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

  jackson:
    serialization:
      fail-on-empty-beans: false

  jpa:
    defer-datasource-initialization: true # Đảm bảo Hibernate tạo bảng xong mới chạy script
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: ${DB_DIALECT:org.hibernate.dialect.SQLServerDialect}

  sql:
    init:
      mode: always # Tự động chạy file data.sql khi khởi động
      # data-locations: classpath:insert_test_data.sql # (Tùy chọn) Chỉ định file SQL cụ thể nếu không dùng file data.sql mặc định

jwt:
  signerKey: ${JWT_SIGNER_KEY:1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij}
  valid-duration: 3600
  refreshable-duration: 36000

brevo:
  api:
    key: ${BREVO_API_KEY:}

sepay:
  token: ${SEPAY_TOKEN:sepay_secret_token}



gemini:
  api:
    key: ${GEMINI_API_KEY:AIzaSyBs9BLQaZWe45ybw3i4Bo-uFNHBYx88WaQ}
    url: ${GEMINI_API_URL:https://generativelanguage.googleapis.com}

# Fallback for Feign
gemini-api-url: "https://generativelanguage.googleapis.com"
