package com.example.AppQuanLiChiTieu.service;

import com.example.AppQuanLiChiTieu.dto.response.CategoryResponse;
import com.example.AppQuanLiChiTieu.entity.Category;
import com.example.AppQuanLiChiTieu.exception.AppException;
import com.example.AppQuanLiChiTieu.exception.ErrorCode;
import com.example.AppQuanLiChiTieu.dto.request.CategoryRequest;
import com.example.AppQuanLiChiTieu.repository.CategoryRepository;
import lombok.AccessLevel;
import lombok.RequiredArgsConstructor;
import lombok.experimental.FieldDefaults;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
@FieldDefaults(level = AccessLevel.PRIVATE)
public class CategoryService {

    final CategoryRepository categoryRepository;

    public CategoryResponse toCategoryResponse(Category category) {
        return CategoryResponse.builder()
                .id(category.getId())
                .name(category.getName())
                .icon(category.getIcon())
                .color(category.getColor())
                .type(category.getType())
                .isMain(Boolean.TRUE.equals(category.getIsMain()))
                .build();
    }

    public List<CategoryResponse> getMyCategories(String type) {
        String currentUserEmail = SecurityContextHolder.getContext().getAuthentication().getName();
        // Initial check
        List<Category> categories = (type != null) 
            ? categoryRepository.findByTypeAndOwnerEmailAndIsDeletedFalse(type, currentUserEmail)
            : categoryRepository.findByOwnerEmailAndIsDeletedFalse(currentUserEmail);

        // Auto-generate default categories if there are NO categories at all
        if (categories.isEmpty() && categoryRepository.findByOwnerEmailAndIsDeletedFalse(currentUserEmail).isEmpty()) {
            synchronized (this) {
                // Double check inside synchronized block
                if (categoryRepository.findByOwnerEmailAndIsDeletedFalse(currentUserEmail).isEmpty()) {
                    categories = autoGenerateDefaultCategories(currentUserEmail);
                } else {
                    categories = (type != null) 
                        ? categoryRepository.findByTypeAndOwnerEmailAndIsDeletedFalse(type, currentUserEmail)
                        : categoryRepository.findByOwnerEmailAndIsDeletedFalse(currentUserEmail);
                }
            }
            
            // If they requested a specific type, filter the newly generated ones
            if (type != null) {
                categories = categories.stream()
                        .filter(c -> c.getType().equals(type))
                        .collect(Collectors.toList());
            }
        }

        return categories.stream().map(this::toCategoryResponse).collect(Collectors.toList());
    }

    private List<Category> autoGenerateDefaultCategories(String currentUserEmail) {
        List<Category> defaults = new ArrayList<>();
        
        // Expenses
        defaults.add(createCategory("Ăn uống", "restaurant", "#EF4444", "EXPENSE", true, currentUserEmail));
        defaults.add(createCategory("Mua sắm", "cart", "#F59E0B", "EXPENSE", false, currentUserEmail));
        defaults.add(createCategory("Đi lại", "bus", "#3B82F6", "EXPENSE", true, currentUserEmail));
        defaults.add(createCategory("Hóa đơn", "receipt", "#8B5CF6", "EXPENSE", true, currentUserEmail));
        defaults.add(createCategory("Giải trí", "game-controller", "#EC4899", "EXPENSE", false, currentUserEmail));
        
        // Incomes
        defaults.add(createCategory("Tiền lương", "cash", "#10B981", "INCOME", true, currentUserEmail));
        defaults.add(createCategory("Tiền thưởng", "gift", "#14B8A6", "INCOME", false, currentUserEmail));
        defaults.add(createCategory("Đầu tư", "trending-up", "#6366F1", "INCOME", false, currentUserEmail));

        return categoryRepository.saveAll(defaults);
    }

    private Category createCategory(String name, String icon, String color, String type, boolean isMain, String ownerEmail) {
        Category cat = new Category();
        cat.setName(name);
        cat.setIcon(icon);
        cat.setColor(color);
        cat.setType(type);
        cat.setIsMain(isMain);
        cat.setIsDefault(true);
        cat.setIsDeleted(false);
        cat.setCreatedAt(Instant.now());
        cat.setOwnerEmail(ownerEmail);
        return cat;
    }

    public CategoryResponse createCategory(CategoryRequest request) {
        String currentUserEmail = SecurityContextHolder.getContext().getAuthentication().getName();
        Category category = new Category();
        category.setName(request.getName());
        category.setIcon(request.getIcon());
        category.setColor(request.getColor());
        category.setOwnerEmail(currentUserEmail);
        category.setType(request.getType());
        category.setIsMain(request.getIsMain() != null ? request.getIsMain() : false);
        category.setIsDefault(false);
        category.setIsDeleted(false);
        category.setCreatedAt(Instant.now());

        Category savedCategory = categoryRepository.save(category);
        return toCategoryResponse(savedCategory);
    }

    public CategoryResponse updateCategory(Integer id, CategoryRequest request) {
        String currentUserEmail = SecurityContextHolder.getContext().getAuthentication().getName();
        Category category = categoryRepository.findByIdAndOwnerEmailAndIsDeletedFalse(id, currentUserEmail)
                .orElseThrow(() -> new AppException(ErrorCode.UNCATEGORIZED_EXCEPTION));

        category.setName(request.getName());
        category.setIcon(request.getIcon());
        category.setColor(request.getColor());
        category.setType(request.getType());
        if (request.getIsMain() != null) {
            category.setIsMain(request.getIsMain());
        }

        Category savedCategory = categoryRepository.save(category);
        return toCategoryResponse(savedCategory);
    }

    public void deleteCategory(Integer id) {
        String currentUserEmail = SecurityContextHolder.getContext().getAuthentication().getName();
        Category category = categoryRepository.findByIdAndOwnerEmailAndIsDeletedFalse(id, currentUserEmail)
                .orElseThrow(() -> new AppException(ErrorCode.UNCATEGORIZED_EXCEPTION));

        // Soft delete
        category.setIsDeleted(true);
        categoryRepository.save(category);
    }
}
