package com.example.AppQuanLiChiTieu.service;

import com.example.AppQuanLiChiTieu.dto.response.CategoryResponse;
import com.example.AppQuanLiChiTieu.entity.Category;
import com.example.AppQuanLiChiTieu.entity.User;
import com.example.AppQuanLiChiTieu.exception.AppException;
import com.example.AppQuanLiChiTieu.exception.ErrorCode;
import com.example.AppQuanLiChiTieu.dto.request.CategoryRequest;
import com.example.AppQuanLiChiTieu.repository.CategoryRepository;
import com.example.AppQuanLiChiTieu.repository.UserRepository;
import lombok.AccessLevel;
import lombok.RequiredArgsConstructor;
import lombok.experimental.FieldDefaults;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
@FieldDefaults(level = AccessLevel.PRIVATE)
public class CategoryService {

    final CategoryRepository categoryRepository;
    final UserRepository userRepository;

    private User getCurrentUser() {
        String email = SecurityContextHolder.getContext().getAuthentication().getName();
        return userRepository.findByEmail(email)
                .orElseThrow(() -> new AppException(ErrorCode.USER_NOT_EXISTED));
    }

    public CategoryResponse toCategoryResponse(Category category) {
        return CategoryResponse.builder()
                .id(category.getId())
                .name(category.getName())
                .icon(category.getIcon())
                .color(category.getColor())
                .type(category.getType())
                .isMain(Boolean.TRUE.equals(category.getIsMain()))
                .build();
    }

    public List<CategoryResponse> getMyCategories(String type) {
        User user = getCurrentUser();
        
        // Initial check
        List<Category> categories = (type != null) 
            ? categoryRepository.findByUserAndTypeAndIsDeletedFalse(user, type)
            : categoryRepository.findByUserAndIsDeletedFalse(user);

        // Auto-generate default categories if the user has NO categories at all
        if (categories.isEmpty() && categoryRepository.findByUserAndIsDeletedFalse(user).isEmpty()) {
            synchronized (this) {
                // Double check inside synchronized block
                if (categoryRepository.findByUserAndIsDeletedFalse(user).isEmpty()) {
                    categories = autoGenerateDefaultCategories(user);
                } else {
                    categories = (type != null) 
                        ? categoryRepository.findByUserAndTypeAndIsDeletedFalse(user, type)
                        : categoryRepository.findByUserAndIsDeletedFalse(user);
                }
            }
            
            // If they requested a specific type, filter the newly generated ones
            if (type != null) {
                categories = categories.stream()
                        .filter(c -> c.getType().equals(type))
                        .collect(Collectors.toList());
            }
        }

        return categories.stream().map(this::toCategoryResponse).collect(Collectors.toList());
    }

    private List<Category> autoGenerateDefaultCategories(User user) {
        List<Category> defaults = new ArrayList<>();
        
        // Expenses
        defaults.add(createCategory(user, "Ăn uống", "restaurant", "#EF4444", "EXPENSE", true));
        defaults.add(createCategory(user, "Mua sắm", "cart", "#F59E0B", "EXPENSE", false));
        defaults.add(createCategory(user, "Đi lại", "bus", "#3B82F6", "EXPENSE", true));
        defaults.add(createCategory(user, "Hóa đơn", "receipt", "#8B5CF6", "EXPENSE", true));
        defaults.add(createCategory(user, "Giải trí", "game-controller", "#EC4899", "EXPENSE", false));
        
        // Incomes
        defaults.add(createCategory(user, "Tiền lương", "cash", "#10B981", "INCOME", true));
        defaults.add(createCategory(user, "Tiền thưởng", "gift", "#14B8A6", "INCOME", false));
        defaults.add(createCategory(user, "Đầu tư", "trending-up", "#6366F1", "INCOME", false));

        return categoryRepository.saveAll(defaults);
    }

    private Category createCategory(User user, String name, String icon, String color, String type, boolean isMain) {
        Category cat = new Category();
        cat.setUser(user);
        cat.setName(name);
        cat.setIcon(icon);
        cat.setColor(color);
        cat.setType(type);
        cat.setIsMain(isMain);
        cat.setIsDefault(true);
        cat.setIsDeleted(false);
        cat.setCreatedAt(Instant.now());
        return cat;
    }

    public CategoryResponse createCategory(CategoryRequest request) {
        User user = getCurrentUser();
        Category category = new Category();
        category.setUser(user);
        category.setName(request.getName());
        category.setIcon(request.getIcon());
        category.setColor(request.getColor());
        category.setType(request.getType());
        category.setIsMain(request.getIsMain() != null ? request.getIsMain() : false);
        category.setIsDefault(false); // User created categories are not default
        category.setIsDeleted(false);
        category.setCreatedAt(Instant.now());

        Category savedCategory = categoryRepository.save(category);
        return toCategoryResponse(savedCategory);
    }

    public CategoryResponse updateCategory(Integer id, CategoryRequest request) {
        User user = getCurrentUser();
        Category category = categoryRepository.findByIdAndUserAndIsDeletedFalse(id, user)
                .orElseThrow(() -> new AppException(ErrorCode.UNCATEGORIZED_EXCEPTION)); // TODO: Add specific NOT_FOUND error if possible

        category.setName(request.getName());
        category.setIcon(request.getIcon());
        category.setColor(request.getColor());
        // Cho phép đổi type thu/chi hay không tuỳ business, hiện đang cho phép đổi
        category.setType(request.getType());
        if (request.getIsMain() != null) {
            category.setIsMain(request.getIsMain());
        }

        Category savedCategory = categoryRepository.save(category);
        return toCategoryResponse(savedCategory);
    }

    public void deleteCategory(Integer id) {
        User user = getCurrentUser();
        Category category = categoryRepository.findByIdAndUserAndIsDeletedFalse(id, user)
                .orElseThrow(() -> new AppException(ErrorCode.UNCATEGORIZED_EXCEPTION));

        // Soft delete
        category.setIsDeleted(true);
        categoryRepository.save(category);
    }
}
